### ISSUE TITLE
Issue with template variables.

### ISSUE THREAD

**Issue by nemanjapetrovic** [mailjet/mailjet-apiv3-templating-samples#2]
Hi guys,

I have an issue sending template variables with v3.1 API:

So here it is:
I have template stored on your website with button HTML like:

```
<center>
    <a href="{{ var:userVerificationLink:"www.google.com" }}" class="btn-verify">
       Verify Address
    </a>
</center>
```

And I am sending API (v3.1, nodejs, npm:"node-mailjet": "3.2.1") request like this one:
```
"Messages ": [{
	"From ": {
		"Email ": "example@example.com",
		"Name ": "Some name"
	},
	"To": [{
		"Email ": "second@second.com",
		"Name ": "Some second"
	}],
	"TemplateID ": 1,
	"Variables": {
		"userVerificationLink": "http://localhost:8080/verify"
	}
}]
```

And my button in received HTML doesn't have at all href link, is there something else to add to this API call or?

**Comment by nemanjapetrovic** [comment]
Will move this issue to your nodejs repository.

**Comment by NicoBru31** [comment]
Hi @nemanjapetrovic are you still facing this issue ?

**Comment by nemanjapetrovic** [comment]
Hi @NicoBru31 ,

you can read more about this at: https://github.com/mailjet/mailjet-apiv3-nodejs/issues/43
